name: "Copilot Setup Steps"

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

permissions:
  contents: read

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest

    steps:
      - name: "Setup Java"
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "21"

      - name: "Checkout sources"
        uses: actions/checkout@v7

      - name: "Copilot setup"
        shell: bash
        env:
          GIT_TOKEN: ${{ secrets.GIT_ACTION_TOKEN }}
        run: |
          echo "Current branch via ref_name: ${{ github.ref_name }}"
          echo "Current branch via head_ref: ${{ github.head_ref }}"
          echo "From directory: $(pwd)"
          echo "Before installing Copilot skills..."
          tree -a
          gh skill install github/awesome-copilot python-mcp-server-generator --agent github-copilot --scope project
          gh skill install github/awesome-copilot pytest-coverage --agent github-copilot --scope user
          echo "After installing Copilot skills..."
          tree -a
          echo "Show git status..."
          git status
